version: "3"

services:
  db:
    container_name: elxpro_blog_db_1
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      POSTGRES_PORT: 5430
    ports:
      - 5430:5432

volumes:
  postgres-data:
